spring.main.allow-circular-references=true
server.port=8081

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.retries=10
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5

app.kafka.replication-factor=1
app.kafka.partitions.api=15
app.kafka.partitions.batch=5
app.kafka.topics.api=user-events-api
app.kafka.topics.batch=user-events-batch
