spring.main.allow-circular-references = true

spring.kafka.bootstrap-servers=localhost:9092

app.kafka.topic.mail-events=mail-events
app.kafka.api-flow.partition-start=0
app.kafka.api-flow.partition-count=15
app.kafka.batch-flow.partition-start=15
app.kafka.batch-flow.partition-count=5
