server.port=8081

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.properties.delivery.timeout.ms=120000
spring.kafka.producer.properties.request.timeout.ms=30000
spring.kafka.producer.properties.batch.size=65536
spring.kafka.producer.properties.buffer.memory=67108864

app.kafka.topic.api=user.api.v1
app.kafka.topic.batch=user.batch.v1
