spring:
  application:
    name: distributed-rate-limiter
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

rate-limiter:
  default-capacity: 10
  default-refill-tokens: 10
  default-refill-period-seconds: 60
