server.port=8082

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fromdummymail@gmail.com
spring.mail.password=holwrjpizmbaytme
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.to=niri1607@gmail.com

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.listener.ack-mode=manual_immediate
spring.kafka.listener.type=single
spring.kafka.listener.missing-topics-fatal=false

app.kafka.topic.api=user.api.v1
app.kafka.topic.batch=user.batch.v1
app.kafka.topic.api-dlt=user.api.v1.dlt
app.kafka.topic.batch-dlt=user.batch.v1.dlt
app.kafka.consumer.group-api=mail-api-flow-v1
app.kafka.consumer.group-batch=mail-batch-flow-v1
app.kafka.consumer.api-concurrency=15
app.kafka.consumer.batch-concurrency=5
