spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email
spring.mail.password=your_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.kafka.bootstrap-servers=localhost:9092

# Flow aware consumer partition allocation
app.kafka.topic=customer-events
app.kafka.total-partitions=20
app.kafka.batch-partition-count=5
app.kafka.api-consumer-concurrency=15
app.kafka.batch-consumer-concurrency=5
app.kafka.max-poll-records=200
app.kafka.max-poll-interval-ms=300000
app.kafka.session-timeout-ms=45000
app.kafka.heartbeat-interval-ms=15000
